### ISSUE TITLE
Vis-network source code build error

### ISSUE THREAD

**Issue by Peter-8960** [visjs/vis-network#1701]
Hi, I clone the vis-network, and want to build secure code. However, amp run build got error below. Does anyone had the same issue? what's the solution?  Thanks!

[!] Error: Cannot find module '@babel/runtime-corejs3/core-js-stable/object/freeze'
Error: Cannot find module '@babel/runtime-corejs3/core-js-stable/object/freeze'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/taofeng/javascript/vis-network/node_modules/vis-dev-utils/dist/vis-dev-utils.cjs.js:31:22)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/taofeng/javascript/vis-network/node_modules/rollup/dist/shared/loadConfigFile.js:622:13)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)

**Comment by Thomaash** [comment]
Hi @Peter-8960,

do you have node 16+? They changed how dependencies are resolved in node 16.

**Comment by Thomaash** [comment]
Hmm, that's weird, that's the exactly same version our CI is running on. Did you try `npm ci` after changing to 16.14.0?

**Comment by Peter-8960** [comment]
unfortunately, after running npm ci, still have the same error.

**Comment by Thomaash** [comment]
I'll need more information (ideally an MWE) to help you. I get no errors with the following Zsh script on node v16.14.0, npm v8.3.1 and today's Arch Linux. What are you running on?
```zsh
git clone --depth 1 git@github.com:visjs/vis-network.git \
&& cd vis-network \
&& npm ci \
&& npm run build
```

**Comment by Peter-8960** [comment]
I run command in macOS (Big Sur v11.6.4.) following Zsh script on node v16.14.0, npm v8.3.1

git clone --depth 1 https://github.com/visjs/vis-network.git \
&& cd vis-network \
&& npm ci \
&& npm run build

**Comment by Peter-8960** [comment]
After manually install each required modules, I got following error. very weird.  

[!] AssertionError: Globals have to be provided for all runtime and peer dependencies but nothing else: expected [ '@babel/plugin-transform-runtime', '@babel/preset-env', '@babel/preset-typescript', '@babel/runtime-corejs3', '@egjs/hammerjs', '@rollup/plugin-babel', '@rollup/plugin-commonjs', '@rollup/plugin-json', '@rollup/plugin-node-resolve', 'babel-plugin-css-modules-transform', 'chai', 'chai-fs', 'component-emitter', 'keycharm', 'opencollective', 'postcss-assets', 'rollup-plugin-analyzer', 'rollup-plugin-babel', 'rollup-plugin-copy', 'rollup-plugin-postcss', 'rollup-plugin-string', 'rollup-plugin-strip-code', 'rollup-plugin-terser', 'rollup-plugin-typescript2', 'timsort', 'typescript', 'uuid', 'vis-data', 'vis-util' ] to deeply equal [ '@egjs/hammerjs', 'component-emitter', 'keycharm', 'timsort', 'uuid', 'vis-data', 'vis-util' ]

**Comment by Thomaash** [comment]
> After manually install each required modules, I got following error. very weird.
> 
> [!] AssertionError: Globals have to be provided for all runtime and peer dependencies but nothing else: expected [ '@babel/plugin-transform-runtime', '@babel/preset-env', '@babel/preset-typescript', '@babel/runtime-corejs3', '@egjs/hammerjs', '@rollup/plugin-babel', '@rollup/plugin-commonjs', '@rollup/plugin-json', '@rollup/plugin-node-resolve', 'babel-plugin-css-modules-transform', 'chai', 'chai-fs', 'component-emitter', 'keycharm', 'opencollective', 'postcss-assets', 'rollup-plugin-analyzer', 'rollup-plugin-babel', 'rollup-plugin-copy', 'rollup-plugin-postcss', 'rollup-plugin-string', 'rollup-plugin-strip-code', 'rollup-plugin-terser', 'rollup-plugin-typescript2', 'timsort', 'typescript', 'uuid', 'vis-data', 'vis-util' ] to deeply equal [ '@egjs/hammerjs', 'component-emitter', 'keycharm', 'timsort', 'uuid', 'vis-data', 'vis-util' ]

This happened because you messed with the dependencies. It comes from an assert that makes sure all dependencies have explicitly set UMD module namespaces. Stuff like rollup-plugin-postcss has no namespace defined because it is not supposed to be present in the website once deployed (I'm 99.99% sure it would just crash if you loaded it anyway).

Could you at the very least provide the clone-install-build.log file of:
```zsh
{
	printf '\n\n%s\n\n\n' '==> Versions' \
	&& node --version \
	&& npm --version \
	&& uname -a \
	&& printf '\n\n%s\n\n\n' '==> Git clone' \
	&& git clone --depth 1 git@github.com:visjs/vis-network.git \
	&& printf '\n\n%s\n\n\n' '==> cd' \
	&& cd vis-network \
	&& printf '\n\n%s\n\n\n' '==> npm ci' \
	&& npm ci \
	&& printf '\n\n%s\n\n\n' '==> npm run build' \
	&& npm run build
} &> clone-install-build.log
```

Ideally provide the whole project dir after it failed.

**Comment by Peter-8960** [comment]
Hi @Thomaash 
Following the above step, here is the content in the clone-install-build.log file:


==> Versions


v16.14.0
8.3.1
Darwin Taos-MBP.attlocal.net 20.6.0 Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64 x86_64


==> Git clone


Cloning into 'vis-network'...


==> cd




==> npm ci


npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.

> vis-network@0.0.0-no-version postinstall
> opencollective postinstall || exit 0

sh: opencollective: command not found

> vis-network@0.0.0-no-version prepare
> husky install

husky - Git hooks installed

added 901 packages, and audited 1108 packages in 53s

103 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (4 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 8.3.1 -> 8.5.5
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.5>
npm notice Run `npm install -g npm@8.5.5` to update!
npm notice 


==> npm run build



> vis-network@0.0.0-no-version build
> npm run build:declarations && npm run build:code && npm run build:legacy:types && npm run build:legacy:code && npm run build:legacy:images


> vis-network@0.0.0-no-version build:declarations
> shx mkdir -p declarations && shx cp -r "types/*" declarations && tsc -p tsconfig.declarations.json


> vis-network@0.0.0-no-version build:code
> rollup --config rollup.build.js

[1m[31m[!] [1mError: Cannot find module '@babel/runtime-corejs3/core-js-stable/object/freeze'
Require stack:
- /Users/taofeng/javascript/vis-network/node_modules/vis-dev-utils/dist/vis-dev-utils.cjs.js
- /Users/taofeng/javascript/vis-network/rollup.build.js
- /usr/local/lib/node_modules/rollup/dist/shared/loadConfigFile.js
- /usr/local/lib/node_modules/rollup/dist/bin/rollup[22m[1m[39m[22m
[2mError: Cannot find module '@babel/runtime-corejs3/core-js-stable/object/freeze'
Require stack:
- /Users/taofeng/javascript/vis-network/node_modules/vis-dev-utils/dist/vis-dev-utils.cjs.js
- /Users/taofeng/javascript/vis-network/rollup.build.js
- /usr/local/lib/node_modules/rollup/dist/shared/loadConfigFile.js
- /usr/local/lib/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/taofeng/javascript/vis-network/node_modules/vis-dev-utils/dist/vis-dev-utils.cjs.js:31:22)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .js] (/usr/local/lib/node_modules/rollup/dist/shared/loadConfigFile.js:617:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)[22m

**Comment by Thomaash** [comment]
Your npm doesn't install everything that it should (it adds 1343 packages on my machine, 901 on yours). Don't you have some special config (`npm config list`), alternative npm repo or cache issues (`npm cache clean --force`)? Not much else comes to my mind at the moment.

PS: Please, don't copy paste outputs into comments, add it as a file attachement. That way I can simply download it and diff it with mine, seeing within seconds where it's different on your machine. When you copy paste it into the comment I get a ton of differences from GitHub's formatting mangling the output, makes it more difficult to find the relevant difference.

**Comment by Peter-8960** [comment]
@Thomaash 
I do not know why npm only installed part of packages. Several way tried, but failed. Eventually, I reinstalled Mac OS, node and npm thoroughly. Now, the issue solved. vis-network can be compiled without error. 
Many thanks for your help, very appreciate it.
