### ISSUE TITLE
 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Eggwise** [visjs/vis-network#1751]
I am getting this error when i use larger datasets (500 items, 2k edges)

I am using the example.

Any idea why it is error'ing ?

```
BarnesHutSolver.js:278 Uncaught RangeError: Maximum call stack size exceeded
    at g.value (BarnesHutSolver.js:278:3)
    at g.value (BarnesHutSolver.js:366:12)
    at g.value (BarnesHutSolver.js:332:16)
```

**Comment by Eggwise** [comment]
The error is occuring in this method:

```
  /**
   * determine in which branch the node will be placed.
   *
   * @param {object} parentBranch
   * @param {Node} node
   * @param {boolean} skipMassUpdate
   * @private
   */
  _placeInTree(parentBranch, node, skipMassUpdate) {
    if (skipMassUpdate != true || skipMassUpdate === undefined) {
      // update the mass of the branch.
      this._updateBranchMass(parentBranch, node);
    }

    const range = parentBranch.children.NW.range;
    let region;
    if (range.maxX > node.x) {
      // in NW or SW
      if (range.maxY > node.y) {
        region = "NW";
      } else {
        region = "SW";
      }
    } else {
      // in NE or SE
      if (range.maxY > node.y) {
        region = "NE";
      } else {
        region = "SE";
      }
    }

    this._placeInRegion(parentBranch, node, region);
  }
```

**Comment by Rico66100** [comment]
Same error for me, recursive function is killing the JS call stack, changing the solver did nothing for me.
I got this on a GWT environment, where the call stack is a bit weird I agree, but maybe going for a simple LOOP instead of recursive function ?

**Comment by willoconnor18** [comment]
I'm getting the same error as well. Were y'all able to resolve it or work around it?

**Comment by Rico66100** [comment]
I managed to bypass the problem by putting the vis-network render in an Iframe. The idea was to cut the callstack of the JS by putting all the vis-network rendering on another entrypoint. It's just a workaround... but it works.

**Comment by kiuusai** [comment]
To be more precise, the recursion is between `_placeInTree` and `_placeInRegion` methods where one call the other and the other call the one and so on...

If it can be avoided, the problem is solved!
