### ISSUE TITLE
v7.4.0 export error

### ISSUE THREAD

**Issue by mikebarkmin** [visjs/vis-network#530]
I am not sure, if this is intended or not, but I am getting an error when build my application with v7.4.0

```
> Build error occurred
/app/node_modules/vis-data/peer/index.js:1
export * from "./esm";
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /app/node_modules/vis-network/peer/umd/vis-network.js:28:82
    at Object.<anonymous> (/app/node_modules/vis-network/peer/umd/vis-network.js:31:2)
    at Module._compile (internal/modules/cjs/loader.js:1147:30) {
  type: 'SyntaxError'
}
error Command failed with exit code 1.
```

Am I doing something wrong or is this an error with the new build system?

**Comment by Thomaash** [comment]
Hi @mikebarkmin,

I tried updating my project and it works fine. This seems like your importing ESM files from something that expects UMD. All the help files (like `peer/index.js`) are in ESM and intended to be used with bundlers that generally can process ESM without issues. If you need UMD you should import with something like `vis-network/peer/umd/vis-network.min.js`.

Though this may be completely off, without more info like whether you're using a bundler, how you import it etc. I can't really help you.

**Comment by mikebarkmin** [comment]
ok thank you. Using the UMD module fixed it.
